### PR TITLE
Organize package dependencies

### PR DESCRIPTION
**Pull request by Karibash**
Removed unnecessary dependencies and relocated package specific dependencies from the root to the appropriate package.

### CODE REVIEW

**Comment by poteboy** [comment]
Thanks!
Kinda off-topic though, after applying the changes from your previous PR, I'm encountering an error with the `tsconfig.json` in each package. It seems to be caused by the addition of the `jest.config.ts` file at the same level as the `src` folder. The error message is as follows:
```sh
File '/path/to/jest.config.ts' is not under 'rootDir' '/path/to/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'
```
One potential solution is to change the rootDir to '.', but I'm a bit hesitant to make this change. Would it be better to change the file extension of `jest.config.ts` to `.js` instead? I would like to hear your thoughts on how to proceed with this issue. @Karibash

**Comment by Karibash** [comment]
@poteboy 
I could not see that error in my local environment.
When does the error occur? (during build or testing?)

**Comment by poteboy** [comment]
@Karibash 
スクリーンショット 2023-05-07 20 41 25

**Comment by Karibash** [comment]
@poteboy 
Ah, I understand now.
How about making it controlled by the include option as shown below instead of rootDir?

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "paths": {},
    "types": ["node"],
    "declaration": true,
    "declarationDir": "dist"
  },
  "include": [
    "src/**/*.ts",
    "jest.config.ts"
  ]
}
```

**Comment by poteboy** [comment]
@Karibash 
Good idea 👍 However, it's not going to work as expected because the TypeScript compiler will look for files relative to the rootDir. To make it work, we should update the include option like this:
```tsconfig.json
"include": [
    "src/**/*.ts",
    "../jest.config.ts"
  ]
```
I will include this change in this PR.

**Review by poteboy — APPROVED** [review]

**Pull request merged**
