### PR TITLE
Update Readme: install kuma as dev dependency

### PR DESCRIPTION
**Pull request by harshsinghatz**

### CODE REVIEW

**Review by poteboy — APPROVED** [review]
Thanks!

**Comment by harshsinghatz** [comment]
No problem, btw does kumi has discord or something?

**Comment by poteboy** [comment]
@harshsinghatz 
We don't have a Discord or similar platform for Kuma just yet. Considering it's still a relatively small OSS, I was thinking of creating one when we hit around 500 stars. However, I'm really happy to hear your interest and I'll consider setting it up earlier than planned. Thank you!

**Comment by harshsinghatz** [comment]
> @harshsinghatz 
> We don't have a Discord or similar platform for Kuma just yet. Considering it's still a relatively small OSS, I was thinking of creating one when we hit around 500 stars. However, I'm really happy to hear your interest and I'll consider setting it up earlier than planned. Thank you!

Looking forward to contributing more!

**Pull request merged**
